# Create full conda environment for development, including some useful tools
name: wrf-devel
channels:
  - conda-forge/label/testing
  - conda-forge
  - scitools
dependencies:
  - python=3
  - metpy=1
  - siphon
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - xarray
  - pandas
  - wrf-python
  - jupyter
  - jupyterlab
  - pytest
  - pytest-cov
  - pytest-flake8
  - pytest-mpl
  - pytest-runner
  - flake8-builtins
  - flake8-comprehensions
  - flake8-copyright
  - flake8-docstrings
  - flake8-import-order
  - flake8-mutable
  - flake8-pep3101
  - flake8-print
  - flake8-quotes
  - pep8-naming
  - pyproj<3.0
  - cartopy
  - dask
  - cmocean
